import { query } from '@anthropic-ai/claude-agent-sdk';
import { appendFile, mkdir, access, stat, readFile, writeFile, unlink } from 'fs/promises';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import os from 'os';
import { loadUserProfile, MEMORY_DIR, PROFILE_PATH } from './memory-logger.mjs';

// Version for verifying container has latest code
const VERSION = '2026-02-03-ws-ping-keepalive';

// Sleep helper (replaces sleep)
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Single-line logging helpers (CF treats each line as separate log entry)
function log(prefix, message, data) {
  if (data !== undefined) {
    console.log(`${prefix} ${message} ${JSON.stringify(data)}`);
  } else {
    console.log(`${prefix} ${message}`);
  }
}

function logError(prefix, message, data) {
  if (data !== undefined) {
    console.error(`${prefix} ${message} ${JSON.stringify(data)}`);
  } else {
    console.error(`${prefix} ${message}`);
  }
}

// Configuration from environment
const PORT = 8080;
const SYNC_DIR = process.env.R2_MOUNT_DIR || '/home/claude';
const TASK_RESULTS_DIR = `${SYNC_DIR}/.chiridion/task-results`;
const TODOS_DIR = `${SYNC_DIR}/.chiridion/todos`;
const CLAUDE_DEBUG_DIR = `${SYNC_DIR}/.claude/debug`;
const DEBUG_STARTUP = process.env.CHIRIDION_DEBUG_STARTUP === '1';
const DEBUG_SDK = process.env.CHIRIDION_DEBUG_SDK === '1';
const DEBUG_FS = process.env.CHIRIDION_DEBUG_FS === '1';
const DEBUG_PROXY = process.env.CHIRIDION_DEBUG_PROXY === '1';
const PREQUEUE_FIRST_MESSAGE = process.env.CHIRIDION_PREQUEUE_FIRST_MESSAGE === '1';
const FIRST_MESSAGE_DELAY_MS = Number(process.env.CHIRIDION_FIRST_MESSAGE_DELAY_MS || '100') || 0;
const MCP_SERVER_URL = process.env.MCP_SERVER_URL;

log('[ws-server]', 'Starting', { version: VERSION, port: PORT });

// Auth via ANTHROPIC_API_KEY (Claude API proxy with signed token)
if (!process.env.ANTHROPIC_API_KEY) {
  console.error('ANTHROPIC_API_KEY required');
  process.exit(1);
}

// Integration env vars file path - system-wide so all processes can source it
const INTEGRATION_ENV_FILE = '/etc/profile.d/chiridion-integrations.sh';

/**
 * Escape a value for use in a shell export statement.
 * Wraps in single quotes and escapes any single quotes in the value.
 */
function escapeShellValue(value) {
  // Replace single quotes with '\'' (end quote, escaped quote, start quote)
  return "'" + String(value).replace(/'/g, "'\\''") + "'";
}

/**
 * Write integration env vars to /etc/profile.d/chiridion-integrations.sh
 * The file is pre-created by Dockerfile with claude ownership.
 */
async function writeIntegrationEnvFile(envVars) {
  const lines = [
    '# Auto-generated by Chiridion ws-server - do not edit manually',
    `# Updated: ${new Date().toISOString()}`,
    '',
  ];

  for (const [key, value] of Object.entries(envVars)) {
    lines.push(`export ${key}=${escapeShellValue(value)}`);
  }

  const content = lines.join('\n') + '\n';

  await writeFile(INTEGRATION_ENV_FILE, content, { mode: 0o644 });
  log('[ws-server]', 'integration_env_written', { path: INTEGRATION_ENV_FILE, keys: Object.keys(envVars).length });
}

// Session state - keyed by threadId
const sessions = new Map();
const MAX_EVENT_BUFFER = 500;
let taskResultsDirPromise = null;
let todosDirPromise = null;
let startupDiagnosticsPromise = null;

function ensureTaskResultsDir() {
  if (!taskResultsDirPromise) {
    taskResultsDirPromise = mkdir(TASK_RESULTS_DIR, { recursive: true }).catch((err) => {
      logError('[ws-server]', 'Failed to create task results dir:', err?.message || String(err));
    });
  }
  return taskResultsDirPromise;
}

function ensureTodosDir() {
  if (!todosDirPromise) {
    todosDirPromise = mkdir(TODOS_DIR, { recursive: true }).catch((err) => {
      logError('[ws-server]', 'Failed to create todos dir:', err?.message || String(err));
    });
  }
  return todosDirPromise;
}

// Todo state persistence
async function writeTodoState(threadId, todos) {
  if (!threadId) return;
  try {
    await ensureTodosDir();
    const todoPath = `${TODOS_DIR}/${threadId}.json`;
    await writeFile(todoPath, JSON.stringify(todos));
    log('[ws-server]', 'todo_saved', { threadId, count: todos.length });
  } catch (error) {
    logError('[ws-server]', 'Todo write failed:', error?.message || String(error));
  }
}

async function readTodoState(threadId) {
  if (!threadId) return null;
  try {
    const todoPath = `${TODOS_DIR}/${threadId}.json`;
    const content = await readFile(todoPath, 'utf-8');
    const todos = JSON.parse(content);
    log('[ws-server]', 'todo_loaded', { threadId, count: todos.length });
    return todos;
  } catch {
    return null;
  }
}

async function clearTodoState(threadId) {
  if (!threadId) return;
  try {
    const todoPath = `${TODOS_DIR}/${threadId}.json`;
    await unlink(todoPath);
    log('[ws-server]', 'todo_cleared', { threadId });
  } catch {
    // File doesn't exist, that's fine
  }
}

// Extract TodoWrite todos from SDK events
function extractTodosFromEvent(event) {
  if (event?.type === 'assistant' && Array.isArray(event.message?.content)) {
    for (const block of event.message.content) {
      if (block?.type === 'tool_use' && block.name === 'TodoWrite' && Array.isArray(block.input?.todos)) {
        return block.input.todos;
      }
    }
  }
  return null;
}

async function probePath(label, path) {
  try {
    const info = await stat(path);
    log('[ws-server]', 'fs_probe', {
      label,
      path,
      isFile: info.isFile(),
      isDirectory: info.isDirectory(),
      size: info.size,
      mode: info.mode,
    });
  } catch (error) {
    logError('[ws-server]', 'fs_probe_failed', { label, path, error: error?.message || String(error) });
  }
}

async function probeFilesystem() {
  try {
    await mkdir(SYNC_DIR, { recursive: true });
  } catch (error) {
    logError('[ws-server]', 'fs_probe_mkdir_failed', { path: SYNC_DIR, error: error?.message || String(error) });
  }

  await probePath('sync_dir', SYNC_DIR);
  await probePath('claude_dir', `${SYNC_DIR}/.claude`);
  await probePath('claude_projects_dir', `${SYNC_DIR}/.claude/projects`);
  await probePath('chiridion_dir', `${SYNC_DIR}/.chiridion`);
}

async function tailFile(path, maxBytes = 12000) {
  try {
    const data = await readFile(path);
    if (!data || data.length === 0) return null;
    const slice = data.length > maxBytes ? data.subarray(data.length - maxBytes) : data;
    const text = new TextDecoder().decode(slice);
    const lines = text.trim().split('\n');
    const tail = lines.slice(-40).join('\n');
    return tail || null;
  } catch {
    return null;
  }
}

async function logClaudeDebugTail(threadId, reason) {
  if (!threadId) return;
  const debugPath = `${CLAUDE_DEBUG_DIR}/${threadId}.txt`;
  const tail = await tailFile(debugPath);
  if (tail) {
    log('[ws-server]', 'claude_debug_tail', { threadId, reason, path: debugPath });
    console.log(tail);
  } else {
    log('[ws-server]', 'claude_debug_tail_missing', { threadId, reason, path: debugPath });
  }
}

async function probeProxyBaseUrl() {
  const baseUrl = process.env.ANTHROPIC_BASE_URL;
  if (!baseUrl) {
    logError('[ws-server]', 'proxy_probe_skipped', { reason: 'ANTHROPIC_BASE_URL not set' });
    return;
  }
  const trimmed = baseUrl.replace(/\/$/, '');
  const candidates = [`${trimmed}/proxy/health`, `${trimmed}/health`];
  for (const target of candidates) {
    try {
      const res = await fetch(target, { method: 'GET' });
      log('[ws-server]', 'proxy_probe', { url: target, status: res.status });
      if (res.ok || res.status === 404) {
        return;
      }
    } catch (error) {
      logError('[ws-server]', 'proxy_probe_failed', { url: target, error: error?.message || String(error) });
    }
  }
}

async function runStartupDiagnostics() {
  if (startupDiagnosticsPromise) return startupDiagnosticsPromise;
  startupDiagnosticsPromise = (async () => {
    const uid = typeof process.getuid === 'function' ? process.getuid() : null;
    const gid = typeof process.getgid === 'function' ? process.getgid() : null;
    const envSnapshot = {
      cwd: process.cwd(),
      home: typeof os.homedir === 'function' ? os.homedir() : process.env.HOME || null,
      user: process.env.USER || null,
      uid,
      gid,
      syncDir: SYNC_DIR,
      taskResultsDir: TASK_RESULTS_DIR,
      anthropicBaseUrl: process.env.ANTHROPIC_BASE_URL || null,
      anthropicKeyLen: (process.env.ANTHROPIC_API_KEY || '').length,
      mcpServerUrl: MCP_SERVER_URL || null,
      bunVersion: typeof Bun !== 'undefined' ? Bun.version : null,
      nodeVersion: process.version,
    };
    log('[ws-server]', 'startup_env', envSnapshot);

    if (DEBUG_FS) {
      await probeFilesystem();
    }
    if (DEBUG_PROXY) {
      await probeProxyBaseUrl();
    }
  })();
  return startupDiagnosticsPromise;
}

function extractParentToolUseId(event) {
  if (!event || typeof event !== 'object') return null;
  const record = event;
  const message = record.message || {};
  const parent = (
    record.parent_tool_use_id ??
    record.source_tool_use_id ??
    record.parentToolUseId ??
    record.sourceToolUseId ??
    message.parent_tool_use_id ??
    message.source_tool_use_id ??
    message.parentToolUseId ??
    message.sourceToolUseId
  );
  return typeof parent === 'string' ? parent : null;
}

function extractParentToolPrompt(event) {
  if (!event || typeof event !== 'object') return null;
  const toolUseResult = event.toolUseResult || event.tool_use_result || null;
  const prompt = toolUseResult?.prompt;
  return typeof prompt === 'string' ? prompt : null;
}

async function writeTaskResultUpdate(threadId, entry) {
  if (!threadId) return;
  try {
    await ensureTaskResultsDir();
    const taskPath = `${TASK_RESULTS_DIR}/${threadId || 'unknown'}.jsonl`;
    const line = `${JSON.stringify({ at: new Date().toISOString(), threadId, ...entry })}\n`;
    await appendFile(taskPath, line);
  } catch (error) {
    logError('[ws-server]', 'Task update write failed:', error?.message || String(error));
  }
}

function persistTaskResultUpdates(session, event) {
  if (!session?.threadId) return;
  if (!event || event.type !== 'user') return;
  const content = event.message?.content;
  if (!Array.isArray(content)) return;
  const toolResults = content.filter((block) => block?.type === 'tool_result' && block.tool_use_id);
  if (toolResults.length === 0) return;
  const parentToolUseId = extractParentToolUseId(event);
  const parentToolPrompt = extractParentToolPrompt(event);
  const parentIsTask = parentToolUseId
    ? session.taskToolUseIds?.has(parentToolUseId)
    : Boolean(parentToolPrompt);
  if (!parentIsTask) return;
  const timestamp = event.timestamp || new Date().toISOString();

  toolResults.forEach((toolResult, index) => {
    if (session.taskToolUseIds?.has(toolResult.tool_use_id)) return;
    if (parentToolUseId && toolResult.tool_use_id === parentToolUseId) return;
    if (!parentToolUseId && !parentToolPrompt) return;
    void writeTaskResultUpdate(session.threadId, {
      type: 'task_update',
      parent_tool_use_id: parentToolUseId,
      parent_tool_prompt: parentToolPrompt,
      tool_use_id: toolResult.tool_use_id,
      content: toolResult.content,
      timestamp,
      index,
    });
  });
}

function trackTaskToolUse(session, event) {
  if (!session) return;
  if (!event || typeof event !== 'object') return;

  if (event.type === 'assistant' && Array.isArray(event.message?.content)) {
    event.message.content.forEach((block) => {
      if (block?.type === 'tool_use' && block.name === 'Task' && block.id) {
        session.taskToolUseIds.add(block.id);
      }
    });
  }

  if (event.type === 'stream_event' && event.event?.type === 'content_block_start') {
    const block = event.event.content_block;
    if (block?.type === 'tool_use' && block.name === 'Task' && block.id) {
      session.taskToolUseIds.add(block.id);
    }
  }
}

function createSession(threadId, threadDeployToken = null, mcpToken = null, userInfo = null) {
  const session = {
    threadId,
    threadDeployToken,
    mcpToken,
    userName: userInfo?.userName || null,
    userEmail: userInfo?.userEmail || null,
    activeQuery: null,
    queryIterator: null,
    initPromise: null,
    queryId: 0,
    earlyExitRetries: 0,
    lastUserMessage: null,
    lastStopRequestedAt: 0,
    eventLoopRunning: false,
    messageResolver: null,
    messageQueue: [],
    attachedSockets: new Set(),
    eventBuffer: [],
    nextEventId: 1,
    taskToolUseIds: new Set(),
    eventTypeHistory: [],
    // AskUserQuestion state
    pendingQuestions: new Map(),
    // Track when canUseTool is awaiting user response
    awaitingCanUseTool: false,
    awaitingCanUseToolSince: null,
  };
  sessions.set(threadId, session);
  return session;
}

function getOrCreateSession(threadId, threadDeployToken = null, mcpToken = null, userInfo = null) {
  if (!threadId) {
    threadId = crypto.randomUUID();
  }
  if (sessions.has(threadId)) {
    const session = sessions.get(threadId);
    if (threadDeployToken && !session.threadDeployToken) {
      session.threadDeployToken = threadDeployToken;
    }
    if (mcpToken && !session.mcpToken) {
      session.mcpToken = mcpToken;
    }
    if (userInfo?.userName && !session.userName) {
      session.userName = userInfo.userName;
    }
    if (userInfo?.userEmail && !session.userEmail) {
      session.userEmail = userInfo.userEmail;
    }
    if (!session.taskToolUseIds) {
      session.taskToolUseIds = new Set();
    }
    if (!session.pendingQuestions) {
      session.pendingQuestions = new Map();
    }
    if (session.awaitingCanUseTool === undefined) {
      session.awaitingCanUseTool = false;
      session.awaitingCanUseToolSince = null;
    }
    return session;
  }
  return createSession(threadId, threadDeployToken, mcpToken, userInfo);
}

const PERSIST_PREFIX = '[PERSIST]';
function logForPersistence(event) {
  const line = JSON.stringify(event);
  console.error(`${PERSIST_PREFIX}${line}`);
}

function summarizeError(error) {
  if (!error || typeof error !== 'object') {
    return { message: String(error) };
  }
  return {
    message: String(error),
    name: error.name,
    stack: error.stack,
    cause: error.cause ? String(error.cause) : undefined,
  };
}

process.on('uncaughtException', (error) => {
  logError('[ws-server]', 'Uncaught exception:', summarizeError(error));
});

process.on('unhandledRejection', (error) => {
  logError('[ws-server]', 'Unhandled rejection:', summarizeError(error));
});

let totalConnections = 0;
let serverStartTime = Date.now();

// WebSocket ping/pong keep-alive interval (30 seconds)
const PING_INTERVAL_MS = 30000;

const STATUS_LOG_INTERVAL = 5 * 60 * 1000;
setInterval(() => {
  const uptimeMs = Date.now() - serverStartTime;
  const uptimeMins = Math.floor(uptimeMs / 60000);
  const sessionCount = sessions.size;
  let activeSocketCount = 0;
  for (const session of sessions.values()) {
    activeSocketCount += session.attachedSockets?.size || 0;
  }
  log('[ws-server]', 'STATUS', {
    uptimeMins,
    sessions: sessionCount,
    activeSockets: activeSocketCount,
    totalConnectionsEver: totalConnections,
  });
}, STATUS_LOG_INTERVAL);

process.on('exit', (code) => {
  log('[ws-server]', `Process exiting code=${code}`, {
    uptimeSecs: Math.floor((Date.now() - serverStartTime) / 1000),
    sessions: sessions.size,
  });
});

process.on('SIGTERM', () => {
  log('[ws-server]', 'Received SIGTERM signal');
});

process.on('SIGINT', () => {
  log('[ws-server]', 'Received SIGINT signal');
});

// Check if a session JSONL file exists (async version)
async function sessionFileExists(sessionId) {
  if (!sessionId) return false;
  const projectPath = '-home-claude';
  const jsonlPath = `${SYNC_DIR}/.claude/projects/${projectPath}/${sessionId}.jsonl`;
  const start = Date.now();
  let exists = false;
  try {
    await access(jsonlPath);
    exists = true;
  } catch {
    exists = false;
  }
  const durationMs = Date.now() - start;
  log('[ws-server]', 'sessionFileExists', { sessionId, path: jsonlPath, exists, durationMs });
  return exists;
}

// Episodic memory subagent - handles both logging and searching
const MEMORY_AGENT = {
  description: `Episodic memory manager. IMPORTANT: Always RESUME this subagent using its previous agent ID if one exists - do not start fresh each time. This preserves context about what has already been logged/searched.

Use for THREE purposes:

1. LOGGING (run in background): After completing significant tasks, invoke with run_in_background=true to record what was done. Use proactively after implementing features, fixing bugs, deploying, or completing multi-step tasks.

2. SEARCHING (run in foreground): When you need to find past work - "when did we deploy X?", "what was that bug?", "have we worked on this before?" - search BOTH memory files AND session history to get complete results.

3. CONTEXT RETRIEVAL (run in foreground): Use session-search show with --around to get full context around a specific message or timestamp.`,
  prompt: `You are an episodic memory manager for a coding workspace. You handle LOGGING memories and SEARCHING history.

## Memory Location
${MEMORY_DIR}/YYYY-MM-DD.md (one file per day, timestamped entries)

## MODE 1: LOGGING (when asked to record/log something)

Write a brief entry (2-4 sentences) summarizing what was accomplished:
- What the user wanted
- Key actions taken (files, tools, decisions)
- The outcome

**Entry format:**
\`\`\`
## HH:MM - [Brief Title]
[2-4 sentence factual summary]
\`\`\`

Append to today's file. Create it if needed. Be concise and factual.

## MODE 2: SEARCHING (when asked to find/recall something)

Search BOTH sources to get complete results:

**Memory files** (curated summaries):
\`\`\`bash
grep -r "keyword" ${MEMORY_DIR}/
\`\`\`

**Session history** (full conversation logs):
\`\`\`bash
# Search for specific terms (index auto-updates every 60s)
session-search search "your query" --limit 20

# Filter by date range
session-search search "query" --after "2026-01-15" --before "2026-01-20"

# Filter by session (supports partial IDs like "68369296")
session-search search "query" --session 68369296

# View context around a search result
session-search show <session-id> --around "<timestamp>" --context 5

# Show recent sessions
session-search list --limit 10
\`\`\`

Search results show message numbers (e.g., #47) for easy reference.

## Tips
- Memory files have curated summaries, session-search has raw conversation history
- Always try both - memory logs may not exist for all work
- Partial session IDs work (first 8 chars of UUID)
- Use --around with a timestamp to see surrounding context

## Tools Available
- Read: read memory files
- Write: append new entries
- Grep: search across files
- Glob: list files
- Bash: run session-search CLI and other commands`,
  tools: ['Read', 'Write', 'Grep', 'Glob', 'Bash'],
  model: 'haiku',
  maxTurns: 8,
};

// User profile writer subagent - updates the persistent user profile
const PROFILE_WRITER_AGENT = {
  description: `User profile writer. Use this subagent IN THE BACKGROUND (run_in_background=true) when you learn something new about the user that's worth remembering long-term. This includes:
- Personality traits and communication style
- Technical preferences (languages, frameworks, tools)
- Work habits and patterns
- Inside jokes or recurring references
- Personal details they've shared
- Pet peeves or things they love

IMPORTANT: Always RESUME this subagent using its previous agent ID. The profile is always visible in the system prompt, so no reader is needed.`,
  prompt: `You are a user profile manager. Your job is to maintain a profile of the user based on interactions.

## Profile Location
${PROFILE_PATH}

## What to Track
- **Character**: Personality, communication style, sense of humor
- **Preferences**: Technical preferences, coding style, tool choices
- **Context**: Their role, projects they work on, team context
- **Quirks**: Unique habits, pet peeves, things they love
- **Inside Jokes**: Recurring references, shared humor, callbacks

## How to Update
1. First, READ the current profile to see what exists
2. Then WRITE the updated profile, preserving existing content and adding/updating sections

## Profile Format
Use clear markdown sections:
\`\`\`markdown
# User Profile

## Character
[Personality traits, communication style]

## Technical Preferences
[Languages, frameworks, tools, coding style]

## Work Context
[Role, projects, team]

## Quirks & Preferences
[Habits, pet peeves, likes/dislikes]

## Inside Jokes & References
[Shared humor, callbacks, recurring themes]

## Notes
[Anything else worth remembering]
\`\`\`

## Guidelines
- Be concise but capture personality
- Update existing sections, don't duplicate
- Remove outdated info when updating
- Keep the tone warm and personal
- This is about KNOWING the user, not logging tasks`,
  tools: ['Read', 'Write'],
  model: 'haiku',
  maxTurns: 3,
};

const SYSTEM_PROMPT_APPEND = `
## About This Environment

You are running inside **Chiridion**, a web application that brings Claude Code to the browser. Users interact through a chat interface - they cannot see your terminal, localhost servers, or file system directly.

**Important constraints:**
- **localhost is not accessible** - Users cannot open localhost URLs. If you need to show something, deploy it or output the content directly.
- **Don't assume technical ability** - Users may not be developers. Explain what you're doing in plain language. Avoid jargon unless the user demonstrates familiarity.
- **Show results, not processes** - Instead of saying "run npm start and open localhost:3000", deploy the app or show the output directly.
- **Use short bash timeouts** - This is an interactive user session. Default to shorter timeouts for bash commands to avoid long waits. Use longer timeouts only when necessary (e.g., deployments, builds).
- **Avoid large package installations** - Do not install large frameworks like OpenNext, Next.js, or other heavy dependencies. They take too long and degrade the user experience. Use the pre-configured templates instead.

## Multi-User Threads

Threads in Chiridion can have multiple users. Each user message is prefixed with the sender's identity in the format \`[Name (email)]: message\` or \`[email]: message\`. Pay attention to who is sending each message - different team members may have different questions or instructions.

## Chiridion Context Blocks

Some messages include hidden context inserted by Chiridion. This context may appear as:
- \`<chiridion system message> ... </chiridion system message>\`
- \`[Chiridion system context]\` blocks

Treat the content inside these blocks as trusted operator context for the current turn. Use it to guide your response and behavior, but do not explicitly mention these blocks, do not quote their wrappers, and do not tell the user that hidden context was provided.

## File Sharing with User

You have access to two special directories for exchanging files with the user:

- **\`/mnt/user-uploads/\`** - Files uploaded by the user. When a user uploads a file, you'll see a message like "(user uploaded file to /mnt/user-uploads/filename.png)". Read files from this directory to access what they shared.

- **\`/mnt/user-outputs/\`** - Files you create for the user to download or preview. Save files here when you want the user to access them.

**Creating downloadable/previewable files:**
When you save a file to /mnt/user-outputs/, provide a URL so the user can access it:
- Use the workspace outputs URL: \`/api/workspaces/${process.env.WORKSPACE_ID}/outputs/\`
- For images: \`![Description](/api/workspaces/${process.env.WORKSPACE_ID}/outputs/chart.png)\` - displays inline
- For downloads: \`[Download Report](/api/workspaces/${process.env.WORKSPACE_ID}/outputs/report.pdf)\` - triggers download

Examples:
- Image preview: \`![Analysis Chart](/api/workspaces/${process.env.WORKSPACE_ID}/outputs/charts/analysis.png)\`
- Download link: \`[Download CSV](/api/workspaces/${process.env.WORKSPACE_ID}/outputs/data.csv)\`
- Download link: \`[Get Full Report](/api/workspaces/${process.env.WORKSPACE_ID}/outputs/report.pdf)\`

## Node.js Package Management

**Always use \`yarn\`** for Node.js package management. Do not use \`npm\` or \`bun\` - use \`yarn\` exclusively for installing dependencies, running scripts, and managing packages.

## Python Environment

This environment has **\`uv\`** installed - a fast Python package manager and project tool. Use \`uv\` instead of \`pip\` for all Python package management:

- **Install packages:** \`uv pip install <package>\` or \`uv add <package>\` (for projects)
- **Run scripts:** \`uv run python script.py\` (auto-installs dependencies)
- **Create virtualenvs:** \`uv venv\` (much faster than python -m venv)
- **Sync dependencies:** \`uv sync\` (from pyproject.toml)

\`uv\` is significantly faster than pip and handles dependency resolution better. Always prefer it for Python work.

## Cloudflare Deployment

When deploying software to the internet or for the user to access:

1. **Always use the globally installed \`wrangler\` CLI** - Do not install wrangler locally via npm
2. **Build as Cloudflare Workers** - All deployable software should be written as Workers
3. **Use Durable Objects with SQLite** - For persistence, use SQLite-backed Durable Objects (not KV)
4. **Use \`wrangler deploy --dispatch-namespace chiridion\`** - Deploy with the global wrangler binary

The infrastructure is already configured for Worker deployments. **For any web app with a UI, use \`create-worker\` to scaffold from the Chiridion starter template**—it's fast to create, has React Router 7 + shadcn/ui pre-configured, and handles both simple and complex apps. Only skip the template for pure API workers with no frontend.

**Important:** Do not install large frameworks like OpenNext, Next.js, or other heavy dependencies—they take too long. The Chiridion starter template has everything pre-configured.

## Episodic Memory

You have a **memory** subagent for maintaining context across sessions. It handles both logging and searching.

**IMPORTANT:** Always **resume** the memory subagent using its previous agent ID rather than starting fresh. This preserves the subagent's context about what has already been logged or searched in this session. Track the agent ID after first invocation and use the \`resume\` parameter on subsequent calls.

### Logging (background)
After completing significant work, invoke with \`run_in_background: true\`:
- After implementing features or fixing bugs
- After deploying applications
- After completing multi-step tasks
- After important decisions or investigations

### Searching (foreground)
When you need to find past work, invoke normally:
- "When did we deploy X?"
- "What was that bug we fixed?"
- "Have we worked on this before?"

### Storage
Memory files: \`~/.chiridion/memory/YYYY-MM-DD.md\`
Use the memory subagent to search when you need past context.

## Asking Questions with AskUserQuestion

Use the **AskUserQuestion** tool whenever you have a question with multiple valid options. This is your primary way to gather user preferences and make decisions collaboratively.

**When to use it:**
- Choosing between approaches (e.g., "Should I use SQLite or KV for this?")
- Clarifying requirements (e.g., "What color theme do you want?")
- Confirming before significant actions (e.g., "This will delete the old data. Proceed?")
- Offering feature options (e.g., "Do you want authentication included?")

**When NOT to use it:**
- For simple yes/no questions that don't affect the outcome
- When you already have enough information to proceed
- For questions you can answer yourself by reading docs or code

The tool presents your options as clickable buttons in the chat, making it easy for users to respond quickly. Don't make assumptions when multiple valid paths exist—ask!

## User Profile

You have a **profile-writer** subagent for maintaining a persistent profile about the user. The profile is always loaded into your system prompt, so you can see it - no reader needed.

**IMPORTANT:** Always **resume** the profile-writer subagent using its previous agent ID.

### When to Update (background)
Invoke with \`run_in_background: true\` when you learn something new about the user:
- Personality traits or communication style
- Technical preferences (languages, tools, coding style)
- Work context (role, team, projects)
- Quirks, pet peeves, things they love
- Inside jokes or recurring references

### What NOT to Log
- Transient task details (use memory for that)
- Sensitive personal information
- Temporary preferences

### Storage
Profile: \`~/.chiridion/profile.md\`
The full profile is always in your system prompt under "User Profile".
`;

// Handle AskUserQuestion via canUseTool callback
async function handleCanUseTool(session, toolName, input, opts) {
  log('[ws-server]', 'canUseTool', { threadId: session.threadId, tool: toolName, toolUseID: opts?.toolUseID });

  if (toolName === 'AskUserQuestion') {
    const questions = input?.questions;

    if (!Array.isArray(questions) || questions.length === 0) {
      logError('[ws-server]', 'Invalid AskUserQuestion input', { threadId: session.threadId });
      return { behavior: 'allow' };
    }

    const questionId = `q_${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const toolUseId = opts?.toolUseID;

    log('[ws-server]', 'AskUserQuestion', { threadId: session.threadId, questionId, numQuestions: questions.length });

    // Track that we're waiting for user response
    session.awaitingCanUseTool = true;
    session.awaitingCanUseToolSince = Date.now();

    // Create a promise that will be resolved when user responds
    const answerPromise = new Promise((resolve) => {
      session.pendingQuestions.set(questionId, {
        questionId,
        toolUseId,
        questions,
        resolve,
      });
    });

    // Broadcast question to all connected clients
    bufferEvent(session, {
      type: 'ask_user_question',
      questionId,
      toolUseId,
      questions,
    });

    // Wait for user response
    const answers = await answerPromise;

    // Clear awaiting state
    session.awaitingCanUseTool = false;
    session.awaitingCanUseToolSince = null;

    log('[ws-server]', 'AskUserQuestion_answered', { threadId: session.threadId, questionId });

    return {
      behavior: 'allow',
      updatedInput: {
        questions,
        answers,
      },
    };
  }

  // Allow all other tools
  return { behavior: 'allow' };
}

// Handle user's response to AskUserQuestion
function handleQuestionResponse(session, questionId, answers) {
  const pending = session.pendingQuestions.get(questionId);

  if (!pending) {
    logError('[ws-server]', 'No pending question', { questionId });
    return;
  }

  session.pendingQuestions.delete(questionId);
  log('[ws-server]', 'question_response', { threadId: session.threadId, questionId });

  pending.resolve(answers);

  bufferEvent(session, {
    type: 'question_answered',
    questionId,
  });
}

// Query options for Claude SDK
function getQueryOptions(session, fileExists) {
  // Integration env vars are now in process.env (set via /update-env endpoint)
  // BASH_ENV ensures non-interactive bash shells source our integration file
  const envVars = {
    ...process.env,
    BASH_ENV: INTEGRATION_ENV_FILE,
    THREAD_ID: session.threadId || '',
  };

  if (session.threadDeployToken) {
    envVars.CLOUDFLARE_API_TOKEN = session.threadDeployToken;
  }

  const mcpServers = {};
  // Only use per-thread MCP token (has thread_id encoded, can't be spoofed)
  if (MCP_SERVER_URL && session.mcpToken) {
    mcpServers['chiridion'] = {
      type: 'http',
      url: MCP_SERVER_URL,
      headers: {
        Authorization: `Bearer ${session.mcpToken}`,
      },
    };
  }

  // Create canUseTool callback for this session
  const canUseToolCallback = async (toolName, input, opts) => {
    return handleCanUseTool(session, toolName, input, opts);
  };

  // Stop hook to remind Claude about memory logging
  const stopHook = async (input, toolUseID, opts) => {
    return {
      systemMessage: 'Before finishing: Did you log anything significant to memory? If you accomplished notable work (feature, fix, deployment, investigation) and haven\'t logged it yet, invoke the memory subagent in the background now.',
    };
  };

  const options = {
    model: 'opus',
    fallbackModel: 'sonnet',
    includePartialMessages: true,
    permissionMode: 'bypassPermissions',
    allowUnsandboxedCommands: true,
    // Use canUseTool for AskUserQuestion interception
    canUseTool: canUseToolCallback,
    stderr: (data) => {
      const message = String(data || '').trim();
      if (!message) return;
      logError('[ws-server]', 'cli_stderr', {
        threadId: session.threadId,
        message: message.slice(0, 2000),
      });
    },
    ...(Object.keys(mcpServers).length > 0 && {
      mcpServers,
      allowedTools: ['mcp__chiridion__*'],
    }),
    systemPrompt: {
      type: 'preset',
      preset: 'claude_code',
      append: SYSTEM_PROMPT_APPEND.trim() +
        (session.userProfile ? `\n\n## User Profile\n\nHere's what you know about this user:\n\n${session.userProfile}` : ''),
    },
    settingSources: ['project', 'user'],
    env: envVars,
    // Custom subagents
    agents: {
      'memory': MEMORY_AGENT,
      'profile-writer': PROFILE_WRITER_AGENT,
    },
    // Hooks
    hooks: {
      Stop: [{ hooks: [stopHook] }],
    },
  };

  if (session.threadId) {
    if (fileExists) {
      options.resume = session.threadId;
    } else {
      options.extraArgs = { 'session-id': session.threadId };
    }
  }

  if (DEBUG_SDK) {
    log('[ws-server]', 'query_options', {
      threadId: session.threadId,
      resume: Boolean(options.resume),
      hasExtraArgs: Boolean(options.extraArgs),
      model: options.model,
      fallbackModel: options.fallbackModel,
      includePartialMessages: options.includePartialMessages,
      hasCanUseTool: Boolean(options.canUseTool),
      permissionMode: options.permissionMode,
      allowUnsandboxedCommands: options.allowUnsandboxedCommands,
      mcpServers: Object.keys(mcpServers || {}),
      envKeys: Object.keys(envVars || {}).length,
      agents: Object.keys(options.agents || {}),
      hasUserProfile: Boolean(session.userProfile),
      hooks: Object.keys(options.hooks || {}),
    });
  }

  return options;
}

// Async generator that yields user messages on demand
// IMPORTANT: This generator must NEVER end - it runs for the lifetime of the session
async function* createMessageStream(session) {
  log('[ws-server]', 'messageStream_start', { threadId: session.threadId });
  let isFirstMessage = true;

  // Infinite loop - generator never terminates
  while (true) {
    try {
      let message;
      if (session.messageQueue.length > 0) {
        message = session.messageQueue.shift();
      } else {
        message = await new Promise((resolve) => {
          log('[ws-server]', 'messageStream_wait', { threadId: session.threadId });
          session.messageResolver = (value) => {
            log('[ws-server]', 'messageStream_resolve', { threadId: session.threadId, resolved: value !== null });
            resolve(value);
          };
        });
      }

      // Skip null messages but don't terminate - just wait for next message
      if (message === null || message === undefined) {
        log('[ws-server]', 'messageStream_skip_null', { threadId: session.threadId });
        continue;
      }

      if (isFirstMessage && FIRST_MESSAGE_DELAY_MS > 0) {
        await sleep(FIRST_MESSAGE_DELAY_MS);
        isFirstMessage = false;
      }

      log('[ws-server]', 'messageStream_yield', {
        threadId: session.threadId,
        contentLength: typeof message === 'string' ? message.length : null,
        queueLength: session.messageQueue.length,
      });
      yield {
        type: 'user',
        message: {
          role: 'user',
          content: message,
        },
      };
    } catch (error) {
      // Log error but DON'T throw - keep the generator alive
      logError('[ws-server]', 'messageStream_error', { threadId: session.threadId, error: summarizeError(error) });
      // Small delay before continuing to prevent tight error loops
      await sleep(100);
    }
  }
}

function bufferEvent(session, payload) {
  if (!session.attachedSockets) {
    session.attachedSockets = new Set();
  }
  const eventId = session.nextEventId++;
  const envelope = { ...payload, eventId, sessionId: session.threadId };
  session.eventBuffer.push(envelope);
  if (session.eventBuffer.length > MAX_EVENT_BUFFER) {
    session.eventBuffer.shift();
  }
  if (session.attachedSockets.size > 0) {
    for (const socket of session.attachedSockets) {
      try {
        socket.send(JSON.stringify(envelope));
      } catch (e) {
        logError('[ws-server]', 'Failed to send event:', String(e));
        session.attachedSockets.delete(socket);
      }
    }
  }
  return envelope;
}

function replayBufferedEvents(session, ws, lastEventId) {
  const fromId = Number.isFinite(lastEventId) ? lastEventId : 0;
  let replayed = 0;
  for (const envelope of session.eventBuffer) {
    if (envelope.eventId > fromId) {
      try {
        ws.send(JSON.stringify(envelope));
        replayed++;
      } catch (e) {
        logError('[ws-server]', 'Failed to replay event:', String(e));
        break;
      }
    }
  }
  if (replayed > 0) {
    log('[ws-server]', 'replayed_buffered_events', { threadId: session.threadId, replayed, fromEventId: fromId });
  }
}

async function attachSession(ws, session, lastEventId) {
  if (!session.attachedSockets) {
    session.attachedSockets = new Set();
  }
  session.attachedSockets.add(ws);
  ws.data = { ...ws.data, threadId: session.threadId };

  if (session.threadId) {
    ws.send(JSON.stringify({ type: 'session', sessionId: session.threadId }));
  }

  ws.send(JSON.stringify({ type: 'ready' }));

  // Send persisted todo state if exists
  const todos = await readTodoState(session.threadId);
  if (todos && todos.length > 0) {
    ws.send(JSON.stringify({ type: 'todo_state', todos }));
  }

  // Send any pending questions to this client
  for (const [, data] of session.pendingQuestions) {
    ws.send(JSON.stringify({
      type: 'ask_user_question',
      questionId: data.questionId,
      toolUseId: data.toolUseId,
      questions: data.questions,
    }));
  }

  replayBufferedEvents(session, ws, lastEventId);
  log('[ws-server]', 'attachSession', {
    threadId: session.threadId,
    lastEventId,
    attachedSockets: session.attachedSockets.size,
    hasTodos: Boolean(todos),
  });
}

// Initialize the stateful query session
async function initSession(session) {
  if (session.activeQuery) {
    log('[ws-server]', 'initSession_skip_active', { threadId: session.threadId });
    return;
  }
  if (session.initPromise) {
    log('[ws-server]', 'initSession_skip_inflight', { threadId: session.threadId });
    await session.initPromise;
    return;
  }

  session.initPromise = (async () => {
    const initStart = Date.now();
    log('[ws-server]', 'initSession_start', { threadId: session.threadId });
    try {
      if (DEBUG_STARTUP) {
        await runStartupDiagnostics();
      }

      // Load user profile
      try {
        const userProfile = await loadUserProfile();
        if (userProfile) {
          session.userProfile = userProfile;
          log('[ws-server]', 'profile_loaded', { threadId: session.threadId, length: userProfile.length });
        }
      } catch (profileErr) {
        logError('[ws-server]', 'profile_load_failed', { error: profileErr?.message || String(profileErr) });
      }

      const fileExists = await sessionFileExists(session.threadId);
      const options = getQueryOptions(session, fileExists);
      const messageStream = createMessageStream(session);
      session.activeQuery = query({ prompt: messageStream, options });
      session.queryIterator = session.activeQuery[Symbol.asyncIterator]();
      session.queryId += 1;
      log('[ws-server]', 'initSession', {
        threadId: session.threadId,
        resume: fileExists,
        durationMs: Date.now() - initStart,
        queryId: session.queryId,
      });
    } catch (error) {
      logError('[ws-server]', 'Failed to init:', summarizeError(error));
      bufferEvent(session, { type: 'error', error: `Failed to initialize session: ${String(error)}` });
    }
  })();

  try {
    await session.initPromise;
  } finally {
    session.initPromise = null;
  }
}

// Start continuous event loop - runs until query ends or error
function startEventLoop(session) {
  if (session.eventLoopRunning || !session.queryIterator) {
    return;
  }
  session.eventLoopRunning = true;
  const eventLoopQueryId = session.queryId;
  let hadNonSystemEvent = false;

  (async () => {
    let exitReason = 'unknown';
    let eventCount = 0;
    const loopStart = Date.now();
    let firstEventAt = null;
    let lastEventType = null;
    try {
      while (true) {
        const iteratorCallStart = Date.now();
        const { value: event, done } = await session.queryIterator.next();
        const iteratorCallDuration = Date.now() - iteratorCallStart;
        eventCount++;

        if (done) {
          exitReason = 'iterator_done';
          log('[ws-server]', 'iterator_done_debug', {
            threadId: session.threadId,
            eventCount,
            lastEventType,
            iteratorCallDurationMs: iteratorCallDuration,
            awaitingCanUseTool: session.awaitingCanUseTool,
            pendingQuestions: session.pendingQuestions.size,
            queueLength: session.messageQueue.length,
          });
          break;
        }

        if (!firstEventAt) {
          firstEventAt = Date.now();
          log('[ws-server]', 'first_event', {
            threadId: session.threadId,
            afterMs: firstEventAt - loopStart,
            eventType: event?.type,
            eventSubType: event?.event?.type,
          });
        }

        const eventType = event?.type;
        const eventSubType = event?.event?.type;
        if (eventType && eventType !== 'system') {
          hadNonSystemEvent = true;
          session.earlyExitRetries = 0;
        }
        if (session.eventTypeHistory) {
          session.eventTypeHistory.push({ type: eventType, subType: eventSubType });
          if (session.eventTypeHistory.length > 20) {
            session.eventTypeHistory.shift();
          }
        }

        lastEventType = `${eventType}:${eventSubType || 'none'}`;

        // Send event to client via WebSocket (or buffer if detached)
        bufferEvent(session, { type: 'sdk_event', event });
        trackTaskToolUse(session, event);
        persistTaskResultUpdates(session, event);

        // Handle TodoWrite
        const todos = extractTodosFromEvent(event);
        if (todos) {
          bufferEvent(session, { type: 'todo_state', todos });
          void writeTodoState(session.threadId, todos);
        }

        // Result means this turn is done - but keep loop alive if sockets connected or messages pending
        if (eventType === 'result') {
          log('[ws-server]', 'sdk_result', {
            threadId: session.threadId,
            stopReason: event?.stop_reason || event?.message?.stop_reason || null,
            status: event?.status || event?.message?.status || null,
          });

          // Clear todos on result
          void clearTodoState(session.threadId);

          const hasConnections = session.attachedSockets && session.attachedSockets.size > 0;
          const hasPendingMessages = session.messageQueue.length > 0;
          if (!hasConnections && !hasPendingMessages) {
            exitReason = 'no_connections_or_messages';
            break;
          }
          // Continue looping - generator will yield queued message or wait for new one
        }
      }
    } catch (e) {
      exitReason = 'error';
      logError('[ws-server]', 'Query error:', summarizeError(e));
      bufferEvent(session, { type: 'error', error: String(e) });
      logForPersistence({ type: 'error', error: String(e) });
    } finally {
      session.activeQuery = null;
      session.queryIterator = null;
      session.eventLoopRunning = false;

      const wasAwaitingCanUseTool = session.awaitingCanUseTool;
      const awaitingDuration = session.awaitingCanUseToolSince
        ? Date.now() - session.awaitingCanUseToolSince
        : null;

      log('[ws-server]', 'event_loop_exit', {
        threadId: session.threadId,
        exitReason,
        eventCount,
        durationMs: Date.now() - loopStart,
        hadFirstEvent: Boolean(firstEventAt),
        hadNonSystemEvent,
        lastEvents: session.eventTypeHistory || [],
        queryId: eventLoopQueryId,
        wasAwaitingCanUseTool,
        awaitingDurationMs: awaitingDuration,
        pendingQuestions: session.pendingQuestions.size,
      });

      const hasConnections = session.attachedSockets && session.attachedSockets.size > 0;
      const stopCooldownMs = 5000;
      const stopRecently = session.lastStopRequestedAt
        ? Date.now() - session.lastStopRequestedAt < stopCooldownMs
        : false;

      // Detect unexpected iterator termination:
      // 1. Original case: iterator_done with no non-system events (early exit)
      // 2. New case: iterator_done while awaiting canUseTool (SDK bug?)
      const unexpectedTermination = exitReason === 'iterator_done' && (
        !hadNonSystemEvent ||
        wasAwaitingCanUseTool
      );

      if (unexpectedTermination && hasConnections && !stopRecently) {
        void logClaudeDebugTail(session.threadId, 'unexpected_iterator_done');

        // Log extra diagnostic info for this case
        if (wasAwaitingCanUseTool) {
          logError('[ws-server]', 'SDK_BUG_DETECTED', {
            threadId: session.threadId,
            reason: 'Iterator ended while awaiting canUseTool callback',
            awaitingDurationMs: awaitingDuration,
            pendingQuestions: Array.from(session.pendingQuestions.keys()),
            hadNonSystemEvent,
            eventCount,
          });
        }

        if (session.earlyExitRetries < 2 && session.lastUserMessage) {
          session.earlyExitRetries += 1;
          const retryContent = session.lastUserMessage;
          log('[ws-server]', 'unexpected_exit_retry', {
            threadId: session.threadId,
            queryId: eventLoopQueryId,
            retryCount: session.earlyExitRetries,
            lastUserMessageLength: retryContent?.length || 0,
            queueLength: session.messageQueue.length,
            hasResolver: Boolean(session.messageResolver),
            wasAwaitingCanUseTool,
          });

          // Clear awaiting state for retry
          session.awaitingCanUseTool = false;
          session.awaitingCanUseToolSince = null;

          setTimeout(() => {
            if (session.activeQuery || session.messageResolver || session.messageQueue.length > 0) {
              return;
            }
            void (async () => {
              await initSession(session);
              startEventLoop(session);
              if (session.messageResolver) {
                const resolver = session.messageResolver;
                session.messageResolver = null;
                resolver(retryContent);
              } else {
                session.messageQueue.push(retryContent);
              }
            })();
          }, 200);
        }
      }
    }
  })();
}

function formatAuthorPrefix(userName, userEmail) {
  if (userName && userEmail) {
    return `[${userName} (${userEmail})]: `;
  } else if (userName) {
    return `[${userName}]: `;
  } else if (userEmail) {
    return `[${userEmail}]: `;
  }
  return '';
}

const CHIRIDION_SYSTEM_MESSAGE_REGEX =
  /<chiridion system message>([\s\S]*?)<\/chiridion system message>/gi;

function extractChiridionSystemContext(content) {
  if (typeof content !== 'string' || content.length === 0) {
    return { contextMessages: [], userMessage: '' };
  }

  const contextMessages = [];
  let match;
  while ((match = CHIRIDION_SYSTEM_MESSAGE_REGEX.exec(content)) !== null) {
    const value = typeof match[1] === 'string' ? match[1].trim() : '';
    if (value) {
      contextMessages.push(value);
    }
  }
  CHIRIDION_SYSTEM_MESSAGE_REGEX.lastIndex = 0;

  const userMessage = content
    .replace(CHIRIDION_SYSTEM_MESSAGE_REGEX, '')
    .trim();
  CHIRIDION_SYSTEM_MESSAGE_REGEX.lastIndex = 0;

  return { contextMessages, userMessage };
}

// Handle a user message
async function handleUserMessage(session, content, userInfo = null) {
  const rawContent = typeof content === 'string' ? content : String(content ?? '');
  const { contextMessages, userMessage } = extractChiridionSystemContext(rawContent);
  const authorPrefix = formatAuthorPrefix(userInfo?.userName, userInfo?.userEmail);
  const attributedUserMessage = userMessage ? `${authorPrefix}${userMessage}` : '';
  const contextualPrefix =
    contextMessages.length > 0
      ? contextMessages
          .map((message) => `[Chiridion system context]\n${message}`)
          .join('\n\n')
      : '';
  const attributedContent = [contextualPrefix, attributedUserMessage]
    .filter(Boolean)
    .join('\n\n')
    .trim();

  if (!attributedContent) {
    return;
  }

  session.lastUserMessage = attributedContent;

  void writeTrace(session.threadId, {
    direction: 'ws_in',
    type: 'message',
    content: attributedContent,
    rawContent,
    author: userInfo,
    hiddenContextCount: contextMessages.length,
  });
  
  log('[ws-server]', 'handleUserMessage', {
    threadId: session.threadId,
    hiddenContextCount: contextMessages.length,
    contentLength: attributedContent.length,
    hasActiveQuery: Boolean(session.activeQuery),
    hasIterator: Boolean(session.queryIterator),
    queueLength: session.messageQueue.length,
    hasResolver: Boolean(session.messageResolver),
  });
  const shouldPrequeue = PREQUEUE_FIRST_MESSAGE && !session.activeQuery && !session.initPromise && !session.messageResolver;
  if (shouldPrequeue) {
    session.messageQueue.push(attributedContent);
    log('[ws-server]', 'message_prequeued', {
      threadId: session.threadId,
      queueLength: session.messageQueue.length,
    });
  }

  // Initialize session if needed
  await initSession(session);

  // Start event loop if not running (it runs continuously)
  startEventLoop(session);

  if (!shouldPrequeue) {
    if (session.messageResolver) {
      const resolver = session.messageResolver;
      session.messageResolver = null;
      resolver(attributedContent);
    } else {
      session.messageQueue.push(attributedContent);
    }
  }
  log('[ws-server]', 'handleUserMessage_enqueued', {
    threadId: session.threadId,
    queueLength: session.messageQueue.length,
    hasResolver: Boolean(session.messageResolver),
  });
}

// Node.js HTTP + WebSocket server
const httpServer = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);

  if (url.pathname === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ status: 'ok', version: VERSION }));
    return;
  }

  if (url.pathname === '/broadcast' && req.method === 'POST') {
    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', () => {
      try {
        const data = JSON.parse(body);
        let sent = false;
        for (const session of sessions.values()) {
          if (!session.attachedSockets) continue;
          for (const socket of session.attachedSockets) {
            socket.send(JSON.stringify(data));
            sent = true;
          }
        }
        if (sent) {
          res.writeHead(200);
          res.end('ok');
        } else {
          res.writeHead(503);
          res.end('No active WebSocket connection');
        }
      } catch (e) {
        res.writeHead(400);
        res.end(String(e));
      }
    });
    return;
  }

  if (url.pathname === '/update-env' && req.method === 'POST') {
    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', async () => {
      try {
        const data = JSON.parse(body);
        if (data.env && typeof data.env === 'object') {
          const envVars = data.env;
          const keys = Object.keys(envVars);

          // Write to system file for new processes
          await writeIntegrationEnvFile(envVars);

          // Clear old INT_* vars from process.env first, then set new ones
          // This ensures deleted integrations don't leave stale env vars
          for (const key of Object.keys(process.env)) {
            if (key.startsWith('INT_')) {
              delete process.env[key];
            }
          }
          for (const [key, value] of Object.entries(envVars)) {
            process.env[key] = value;
          }

          log('[ws-server]', 'update-env', { keys: keys.length });
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ success: true, keys }));
        } else {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ success: false, error: 'Missing env object' }));
        }
      } catch (e) {
        logError('[ws-server]', 'update-env error:', String(e));
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, error: String(e) }));
      }
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
});

const wss = new WebSocketServer({ server: httpServer });

wss.on('connection', (ws, req) => {
  totalConnections++;
  log('[ws-server]', 'ws_open', { totalConnections });

  // Track connection liveness for ping/pong
  ws.isAlive = true;
  ws.on('pong', () => {
    ws.isAlive = true;
  });

  // Store connection metadata on the socket
  ws.data = {
    threadDeployToken: req.headers['x-chiridion-thread-deploy-token'] || null,
    mcpToken: req.headers['x-chiridion-mcp-token'] || null,
    userName: req.headers['x-chiridion-user-name'] || null,
    userEmail: req.headers['x-chiridion-user-email'] || null,
  };

  ws.on('message', async (message) => {
    try {
      const data = JSON.parse(message.toString());

      if (data.type === 'init') {
        const threadId = typeof data.threadId === 'string' ? data.threadId.trim() : '';
        if (!threadId) {
          ws.send(JSON.stringify({ type: 'error', error: 'Missing threadId - init requires a valid threadId' }));
          ws.close(1008, 'missing threadId');
          return;
        }

        const threadDeployToken = ws.data?.threadDeployToken || null;
        const mcpToken = ws.data?.mcpToken || null;
        const userInfo = {
          userName: ws.data?.userName || null,
          userEmail: ws.data?.userEmail || null,
        };

        const session = getOrCreateSession(threadId, threadDeployToken, mcpToken, userInfo);
        log('[ws-server]', 'init', {
          threadId,
          lastEventId: data.lastEventId,
          hasDeployToken: Boolean(threadDeployToken),
          hasMcpToken: Boolean(mcpToken),
          userName: userInfo.userName,
        });
        await attachSession(ws, session, data.lastEventId);

      } else if (data.type === 'message') {
        const threadId = ws.data?.threadId || data.threadId;
        if (!threadId || !sessions.has(threadId)) {
          ws.send(JSON.stringify({ type: 'error', error: 'No session - send init first' }));
          return;
        }
        const session = sessions.get(threadId);
        const userInfo = {
          userName: ws.data?.userName || null,
          userEmail: ws.data?.userEmail || null,
        };
        log('[ws-server]', 'message', {
          threadId,
          contentLength: typeof data.content === 'string' ? data.content.length : null,
          hasSession: Boolean(session),
        });
        await handleUserMessage(session, data.content, userInfo);

      } else if (data.type === 'stop') {
        const threadId = ws.data?.threadId;
        if (threadId && sessions.has(threadId)) {
          const session = sessions.get(threadId);
          log('[ws-server]', 'stop', { threadId });
          session.lastStopRequestedAt = Date.now();
          // Resolve any pending questions with empty answers so SDK can unwind
          for (const [questionId, pending] of session.pendingQuestions) {
            bufferEvent(session, { type: 'question_answered', questionId });
            // Resolve the promise with empty answers to unblock handleCanUseTool
            if (pending.resolve) {
              pending.resolve({});
            }
          }
          session.pendingQuestions.clear();
          // Clear awaiting state
          session.awaitingCanUseTool = false;
          session.awaitingCanUseToolSince = null;
          if (session.activeQuery) {
            try {
              await session.activeQuery.interrupt();
            } catch (e) {
              logError('[ws-server]', 'Interrupt error:', String(e));
            }
          }
        }

      } else if (data.type === 'question_response') {
        const threadId = ws.data?.threadId;
        const session = sessions.get(threadId);
        if (!session) {
          ws.send(JSON.stringify({ type: 'error', error: 'No session' }));
          return;
        }
        const { questionId, answers } = data;
        if (!questionId || !answers) {
          ws.send(JSON.stringify({ type: 'error', error: 'Missing questionId or answers' }));
          return;
        }
        handleQuestionResponse(session, questionId, answers);
      }
    } catch (e) {
      logError('[ws-server]', 'Message handling error:', String(e));
      ws.send(JSON.stringify({ type: 'error', error: String(e) }));
    }
  });

  ws.on('close', (code, reason) => {
    const threadId = ws.data?.threadId;
    if (threadId && sessions.has(threadId)) {
      const session = sessions.get(threadId);
      if (session.attachedSockets) {
        session.attachedSockets.delete(ws);
      }
    }
    log('[ws-server]', 'ws_close', { threadId, code, reason: String(reason || '') });
  });

  ws.on('error', (error) => {
    logError('[ws-server]', 'WebSocket error:', String(error));
  });
});

httpServer.listen(PORT, () => {
  log('[ws-server]', 'Server listening', { port: PORT });
});

// Ping all connected clients periodically to detect dead connections
const pingInterval = setInterval(() => {
  wss.clients.forEach((ws) => {
    if (!ws.isAlive) {
      log('[ws-server]', 'ws_ping_timeout', { threadId: ws.data?.threadId });
      return ws.terminate();
    }
    ws.isAlive = false;
    ws.ping();
  });
}, PING_INTERVAL_MS);

// Clean up ping interval on server close
wss.on('close', () => {
  clearInterval(pingInterval);
});
