nodeLinker: pnp

# Store cache locally in .yarn/cache for portability
enableGlobalCache: false

# Use local Verdaccio registry for wrangler
npmRegistryServer: "http://localhost:4873"
unsafeHttpWhitelist:
  - "localhost"
