export type ProjectScaffoldTemplate = "worker" | "api" | "react-router";

export interface ProjectScaffoldFile {
  path: string;
  content: string;
}

export interface ProjectScaffoldResult {
  template: ProjectScaffoldTemplate;
  filesWritten: string[];
  filesSkipped: string[];
}

export function normalizeProjectScaffoldTemplate(value: unknown): ProjectScaffoldTemplate {
  if (value === undefined || value === null || value === "") return "react-router";
  if (value === "worker") return "worker";
  if (value === "api") return "api";
  if (value === "react-router") return "react-router";
  throw new Error('template must be "worker", "api", or "react-router"');
}

function scaffoldPackageName(projectName: string): string {
  return projectName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "camelai-project";
}

function escapeXmlText(value: string): string {
  const escapes: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&apos;",
  };
  return value.replace(/[&<>"']/g, (char) => escapes[char] ?? char);
}

function defaultWorkerScaffoldFiles(
  projectName: string,
  scriptName: string,
  template: ProjectScaffoldTemplate,
): ProjectScaffoldFile[] {
  const packageName = scaffoldPackageName(projectName);
  const title = template === "api" ? "DO-backed API Worker" : "DO-backed Worker";
  return [
    {
      path: "/package.json",
      content: `${JSON.stringify({
        name: packageName,
        private: true,
        type: "module",
        scripts: {
          build: "tsc --noEmit && bun build src/index.ts --target=browser --format=esm --outfile=build/server/index.js && bun scripts/write-build-manifest.mjs",
          deploy: "wrangler deploy",
        },
        devDependencies: {
          "@cloudflare/workers-types": "^4.20260629.1",
          typescript: "^5.9.2",
          wrangler: "^4.97.0",
        },
      }, null, 2)}\n`,
    },
    {
      path: "/wrangler.jsonc",
      content: `${JSON.stringify({
        name: scriptName,
        main: "src/index.ts",
        compatibility_date: "2026-06-01",
      }, null, 2)}\n`,
    },
    {
      path: "/tsconfig.json",
      content: `${JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          lib: ["ES2022"],
          types: ["@cloudflare/workers-types"],
          strict: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: ["src/**/*.ts", "scripts/**/*.mjs"],
      }, null, 2)}\n`,
    },
    {
      path: "/src/index.ts",
      content: `export interface Env {}\n\nexport default {\n  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {\n    const url = new URL(request.url);\n\n    if (url.pathname === "/health") {\n      return Response.json({ ok: true, project: ${JSON.stringify(packageName)} });\n    }\n\n    return new Response(${JSON.stringify(`Hello from ${projectName}!`)}, {\n      headers: { "content-type": "text/plain; charset=utf-8" },\n    });\n  },\n} satisfies ExportedHandler<Env>;\n`,
    },
    {
      path: "/scripts/write-build-manifest.mjs",
      content: [
        `import { mkdir, readFile, writeFile } from "node:fs/promises";`,
        ``,
        `const config = JSON.parse(await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8"));`,
        `const manifest = { ...config, main_module: "index.js" };`,
        `delete manifest.main;`,
        ``,
        `await mkdir(new URL("../build/server", import.meta.url), { recursive: true });`,
        `await writeFile(`,
        `  new URL("../build/server/wrangler.json", import.meta.url),`,
        "  `${JSON.stringify(manifest, null, 2)}\\n`,",
        `);`,
        ``,
      ].join("\n"),
    },
    {
      path: "/README.md",
      content: `# ${projectName}\n\n${title} scaffolded by camelAI.\n\n## Commands\n\n- \`bun install\` installs explicit dev dependencies.\n- \`bun run build\` type-checks, bundles \`src/index.ts\`, and writes \`build/server/wrangler.json\` for the platform deploy pipeline.\n- \`bun run deploy\` is included for compatibility; camelAI's \`deploy_project\` uses the platform direct-deploy path instead of exposing Cloudflare credentials to this project.\n\nBuild scripts must declare every CLI they use in \`dependencies\` or \`devDependencies\`; package scripts can then resolve those binaries from \`node_modules/.bin\`.\n`,
    },
  ];
}

function defaultReactRouterScaffoldFiles(projectName: string, scriptName: string): ProjectScaffoldFile[] {
  const packageName = scaffoldPackageName(projectName);
  const svgProjectName = escapeXmlText(projectName);
  const file = (lines: string[]) => `${lines.join("\n")}\n`;
  return [
    {
      path: "/package.json",
      content: `${JSON.stringify({
        name: packageName,
        private: true,
        type: "module",
        scripts: {
          dev: "react-router dev",
          build: "react-router build && node ./scripts/build-manifest.mjs",
          deploy: "wrangler deploy",
          typecheck: "react-router typegen && tsc --noEmit",
        },
        dependencies: {
          "@react-router/cloudflare": "^7.16.0",
          "class-variance-authority": "^0.7.1",
          clsx: "^2.1.1",
          "lucide-react": "^0.562.0",
          "radix-ui": "^1.4.3",
          react: "^19.2.0",
          "react-dom": "^19.2.0",
          "react-router": "^7.16.0",
          "tailwind-merge": "^3.4.0",
          "tw-animate-css": "^1.4.0",
        },
        devDependencies: {
          "@cloudflare/workers-types": "^4.20260629.1",
          "@react-router/dev": "^7.16.0",
          "@tailwindcss/vite": "^4.3.0",
          "@types/react": "^19.2.0",
          "@types/react-dom": "^19.2.0",
          esbuild: "^0.28.1",
          tailwindcss: "^4.1.13",
          typescript: "^5.9.2",
          vite: "^8.0.16",
          "vite-tsconfig-paths": "^5.1.4",
          wrangler: "^4.97.0",
        },
      }, null, 2)}\n`,
    },
    {
      path: "/wrangler.jsonc",
      content: `${JSON.stringify({
        name: scriptName,
        main: "./workers/app.ts",
        compatibility_date: "2026-06-01",
        compatibility_flags: ["nodejs_compat"],
        assets: {
          directory: "./public/",
          binding: "ASSETS",
        },
      }, null, 2)}\n`,
    },
    {
      path: "/tsconfig.json",
      content: `${JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          jsx: "react-jsx",
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          types: ["@cloudflare/workers-types", "vite/client"],
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          allowSyntheticDefaultImports: true,
          esModuleInterop: true,
          baseUrl: ".",
          paths: {
            "~/*": ["./app/*"],
          },
        },
        include: ["app/**/*.ts", "app/**/*.tsx", "workers/**/*.ts", "scripts/**/*.mjs", "vite.config.ts", "react-router.config.ts"],
      }, null, 2)}\n`,
    },
    {
      path: "/vite.config.ts",
      content: file([
        `import { reactRouter } from "@react-router/dev/vite";`,
        `import { cloudflareDevProxy } from "@react-router/dev/vite/cloudflare";`,
        `import tailwindcss from "@tailwindcss/vite";`,
        `import { defineConfig } from "vite";`,
        `import tsconfigPaths from "vite-tsconfig-paths";`,
        ``,
        `export default defineConfig({`,
        `  plugins: [cloudflareDevProxy(), tailwindcss(), reactRouter(), tsconfigPaths()],`,
        `  ssr: {`,
        `    noExternal: true,`,
        `    target: "webworker",`,
        `  },`,
        `});`,
      ]),
    },
    {
      path: "/react-router.config.ts",
      content: file([
        `import type { Config } from "@react-router/dev/config";`,
        ``,
        `export default {`,
        `  ssr: true,`,
        `} satisfies Config;`,
      ]),
    },
    {
      path: "/app/root.tsx",
      content: file([
        `import type { ReactNode } from "react";`,
        `import { isRouteErrorResponse, Links, Meta, Outlet, Scripts, ScrollRestoration } from "react-router";`,
        `import type { Route } from "./+types/root";`,
        `import "./app.css";`,
        ``,
        `export const links: Route.LinksFunction = () => [`,
        `  { rel: "preconnect", href: "https://fonts.googleapis.com" },`,
        `  { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },`,
        `  { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" },`,
        `];`,
        ``,
        `export function Layout({ children }: { children: ReactNode }) {`,
        `  return (`,
        `    <html lang="en">`,
        `      <head>`,
        `        <meta charSet="utf-8" />`,
        `        <meta name="viewport" content="width=device-width, initial-scale=1" />`,
        `        <Meta />`,
        `        <Links />`,
        `      </head>`,
        `      <body>`,
        `        {children}`,
        `        <ScrollRestoration />`,
        `        <Scripts />`,
        `      </body>`,
        `    </html>`,
        `  );`,
        `}`,
        ``,
        `export default function App() {`,
        `  return <Outlet />;`,
        `}`,
        ``,
        `export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {`,
        `  const status = isRouteErrorResponse(error) ? error.status : 500;`,
        `  const message = isRouteErrorResponse(error) ? error.statusText : error instanceof Error ? error.message : "Unexpected error";`,
        ``,
        `  return (`,
        `    <main className="mx-auto flex min-h-svh w-full max-w-3xl flex-col items-start justify-center gap-4 px-6 py-16">`,
        `      <p className="text-sm font-medium text-muted-foreground">{status}</p>`,
        `      <h1 className="font-display text-4xl font-semibold tracking-tight">Something went wrong</h1>`,
        `      <p className="text-muted-foreground">{message}</p>`,
        `    </main>`,
        `  );`,
        `}`,
      ]),
    },
    {
      path: "/components.json",
      content: `${JSON.stringify({
        "$schema": "https://ui.shadcn.com/schema.json",
        style: "new-york",
        rsc: false,
        tsx: true,
        tailwind: {
          config: "",
          css: "app/app.css",
          baseColor: "zinc",
          cssVariables: true,
          prefix: "",
        },
        aliases: {
          components: "~/components",
          utils: "~/lib/utils",
          ui: "~/components/ui",
          lib: "~/lib",
          hooks: "~/hooks",
        },
        iconLibrary: "lucide",
      }, null, 2)}\n`,
    },
    {
      path: "/app/app.css",
      content: file([
        `@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap");`,
        `@import "tailwindcss";`,
        `@import "tw-animate-css";`,
        ``,
        `@custom-variant dark (&:is(.dark *));`,
        ``,
        `:root {`,
        `  --radius: 0.75rem;`,
        `  --background: oklch(1 0 0);`,
        `  --foreground: oklch(0.141 0.005 285.823);`,
        `  --card: oklch(1 0 0);`,
        `  --card-foreground: oklch(0.141 0.005 285.823);`,
        `  --popover: oklch(1 0 0);`,
        `  --popover-foreground: oklch(0.141 0.005 285.823);`,
        `  --primary: oklch(0.21 0.006 285.885);`,
        `  --primary-foreground: oklch(0.985 0 0);`,
        `  --secondary: oklch(0.967 0.001 286.375);`,
        `  --secondary-foreground: oklch(0.21 0.006 285.885);`,
        `  --muted: oklch(0.967 0.001 286.375);`,
        `  --muted-foreground: oklch(0.552 0.016 285.938);`,
        `  --accent: oklch(0.967 0.001 286.375);`,
        `  --accent-foreground: oklch(0.21 0.006 285.885);`,
        `  --destructive: oklch(0.577 0.245 27.325);`,
        `  --border: oklch(0.92 0.004 286.32);`,
        `  --input: oklch(0.92 0.004 286.32);`,
        `  --ring: oklch(0.705 0.015 286.067);`,
        `}`,
        ``,
        `.dark {`,
        `  --background: oklch(0.141 0.005 285.823);`,
        `  --foreground: oklch(0.985 0 0);`,
        `  --card: oklch(0.21 0.006 285.885);`,
        `  --card-foreground: oklch(0.985 0 0);`,
        `  --popover: oklch(0.21 0.006 285.885);`,
        `  --popover-foreground: oklch(0.985 0 0);`,
        `  --primary: oklch(0.92 0.004 286.32);`,
        `  --primary-foreground: oklch(0.21 0.006 285.885);`,
        `  --secondary: oklch(0.274 0.006 286.033);`,
        `  --secondary-foreground: oklch(0.985 0 0);`,
        `  --muted: oklch(0.274 0.006 286.033);`,
        `  --muted-foreground: oklch(0.705 0.015 286.067);`,
        `  --accent: oklch(0.274 0.006 286.033);`,
        `  --accent-foreground: oklch(0.985 0 0);`,
        `  --destructive: oklch(0.704 0.191 22.216);`,
        `  --border: oklch(1 0 0 / 10%);`,
        `  --input: oklch(1 0 0 / 15%);`,
        `  --ring: oklch(0.552 0.016 285.938);`,
        `}`,
        ``,
        `@theme inline {`,
        `  --font-sans: "Inter", ui-sans-serif, system-ui, sans-serif;`,
        `  --font-display: "Space Grotesk", "Inter", ui-sans-serif, system-ui, sans-serif;`,
        `  --color-background: var(--background);`,
        `  --color-foreground: var(--foreground);`,
        `  --color-card: var(--card);`,
        `  --color-card-foreground: var(--card-foreground);`,
        `  --color-popover: var(--popover);`,
        `  --color-popover-foreground: var(--popover-foreground);`,
        `  --color-primary: var(--primary);`,
        `  --color-primary-foreground: var(--primary-foreground);`,
        `  --color-secondary: var(--secondary);`,
        `  --color-secondary-foreground: var(--secondary-foreground);`,
        `  --color-muted: var(--muted);`,
        `  --color-muted-foreground: var(--muted-foreground);`,
        `  --color-accent: var(--accent);`,
        `  --color-accent-foreground: var(--accent-foreground);`,
        `  --color-destructive: var(--destructive);`,
        `  --color-border: var(--border);`,
        `  --color-input: var(--input);`,
        `  --color-ring: var(--ring);`,
        `  --radius-sm: calc(var(--radius) - 4px);`,
        `  --radius-md: calc(var(--radius) - 2px);`,
        `  --radius-lg: var(--radius);`,
        `  --radius-xl: calc(var(--radius) + 4px);`,
        `}`,
        ``,
        `@layer base {`,
        `  * {`,
        `    @apply border-border outline-ring/50;`,
        `  }`,
        ``,
        `  body {`,
        `    @apply bg-background text-foreground font-sans antialiased;`,
        `  }`,
        ``,
        `  ::selection {`,
        `    @apply bg-primary text-primary-foreground;`,
        `  }`,
        `}`,
      ]),
    },
    {
      path: "/app/lib/utils.ts",
      content: file([
        `import { clsx, type ClassValue } from "clsx";`,
        `import { twMerge } from "tailwind-merge";`,
        ``,
        `export function cn(...inputs: ClassValue[]) {`,
        `  return twMerge(clsx(inputs));`,
        `}`,
      ]),
    },
    {
      path: "/app/components/ui/button.tsx",
      content: file([
        `import * as React from "react";`,
        `import { cva, type VariantProps } from "class-variance-authority";`,
        `import { Slot } from "radix-ui";`,
        ``,
        `import { cn } from "~/lib/utils";`,
        ``,
        `const buttonVariants = cva(`,
        `  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",`,
        `  {`,
        `    variants: {`,
        `      variant: {`,
        `        default: "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",`,
        `        destructive: "bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40",`,
        `        outline: "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground",`,
        `        secondary: "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",`,
        `        ghost: "hover:bg-accent hover:text-accent-foreground",`,
        `        link: "text-primary underline-offset-4 hover:underline",`,
        `      },`,
        `      size: {`,
        `        default: "h-9 px-4 py-2 has-[>svg]:px-3",`,
        `        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",`,
        `        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",`,
        `        icon: "size-9",`,
        `      },`,
        `    },`,
        `    defaultVariants: {`,
        `      variant: "default",`,
        `      size: "default",`,
        `    },`,
        `  },`,
        `);`,
        ``,
        `function Button({`,
        `  className,`,
        `  variant,`,
        `  size,`,
        `  asChild = false,`,
        `  ...props`,
        `}: React.ComponentProps<"button"> &`,
        `  VariantProps<typeof buttonVariants> & {`,
        `    asChild?: boolean;`,
        `  }) {`,
        `  const Comp = asChild ? Slot.Root : "button";`,
        ``,
        `  return (`,
        `    <Comp`,
        `      data-slot="button"`,
        `      className={cn(buttonVariants({ variant, size, className }))}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `export { Button, buttonVariants };`,
      ]),
    },
    {
      path: "/app/components/ui/badge.tsx",
      content: file([
        `import * as React from "react";`,
        `import { cva, type VariantProps } from "class-variance-authority";`,
        `import { Slot } from "radix-ui";`,
        ``,
        `import { cn } from "~/lib/utils";`,
        ``,
        `const badgeVariants = cva(`,
        `  "inline-flex items-center justify-center rounded-md border px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 gap-1 [&>svg]:size-3 focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] transition-colors overflow-hidden",`,
        `  {`,
        `    variants: {`,
        `      variant: {`,
        `        default: "border-transparent bg-primary text-primary-foreground",`,
        `        secondary: "border-transparent bg-secondary text-secondary-foreground",`,
        `        destructive: "border-transparent bg-destructive text-white",`,
        `        outline: "text-foreground",`,
        `      },`,
        `    },`,
        `    defaultVariants: {`,
        `      variant: "default",`,
        `    },`,
        `  },`,
        `);`,
        ``,
        `function Badge({`,
        `  className,`,
        `  variant,`,
        `  asChild = false,`,
        `  ...props`,
        `}: React.ComponentProps<"span"> &`,
        `  VariantProps<typeof badgeVariants> & { asChild?: boolean }) {`,
        `  const Comp = asChild ? Slot.Root : "span";`,
        ``,
        `  return (`,
        `    <Comp`,
        `      data-slot="badge"`,
        `      className={cn(badgeVariants({ variant }), className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `export { Badge, badgeVariants };`,
      ]),
    },
    {
      path: "/app/components/ui/card.tsx",
      content: file([
        `import * as React from "react";`,
        ``,
        `import { cn } from "~/lib/utils";`,
        ``,
        `function Card({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card"`,
        `      className={cn("bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `function CardHeader({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card-header"`,
        `      className={cn("grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `function CardTitle({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card-title"`,
        `      className={cn("leading-none font-semibold", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `function CardDescription({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card-description"`,
        `      className={cn("text-muted-foreground text-sm", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `function CardContent({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card-content"`,
        `      className={cn("px-6", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `function CardFooter({ className, ...props }: React.ComponentProps<"div">) {`,
        `  return (`,
        `    <div`,
        `      data-slot="card-footer"`,
        `      className={cn("flex items-center px-6", className)}`,
        `      {...props}`,
        `    />`,
        `  );`,
        `}`,
        ``,
        `export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };`,
      ]),
    },
    {
      path: "/app/routes.ts",
      content: file([
        `import { index, type RouteConfig } from "@react-router/dev/routes";`,
        ``,
        `export default [index("routes/home.tsx")] satisfies RouteConfig;`,
      ]),
    },
    {
      path: "/app/routes/home.tsx",
      content: file([
        `import { ArrowRight, Cloud, Code2, Sparkles } from "lucide-react";`,
        ``,
        `import { Badge } from "~/components/ui/badge";`,
        `import { Button } from "~/components/ui/button";`,
        `import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";`,
        ``,
        `export function meta() {`,
        `  return [`,
        `    { title: ${JSON.stringify(projectName)} },`,
        `    { name: "description", content: "A polished camelAI React Router app" },`,
        `    { property: "og:title", content: ${JSON.stringify(projectName)} },`,
        `    { property: "og:description", content: "Built with React Router, Tailwind, and shadcn-style primitives." },`,
        `    { property: "og:image", content: "/og-image.svg" },`,
        `    { name: "twitter:card", content: "summary_large_image" },`,
        `    { name: "twitter:image", content: "/og-image.svg" },`,
        `  ];`,
        `}`,
        ``,
        `export default function Home() {`,
        `  return (`,
        `    <main className="min-h-svh overflow-hidden bg-[radial-gradient(circle_at_top_left,rgba(244,244,245,0.9),transparent_32rem)]">`,
        `      <section className="mx-auto grid min-h-svh w-full max-w-6xl items-center gap-10 px-6 py-16 lg:grid-cols-[1.15fr_0.85fr] lg:px-8">`,
        `        <div className="space-y-8">`,
        `          <Badge variant="outline" className="bg-background/80 backdrop-blur">`,
        `            <Sparkles className="size-3" />`,
        `            React Router + Tailwind scaffold`,
        `          </Badge>`,
        ``,
        `          <div className="space-y-5">`,
        `            <h1 className="font-display text-5xl font-semibold tracking-tight text-balance md:text-7xl">`,
        `              <span>{${JSON.stringify(projectName)}}</span>`,
        `              <span className="block text-muted-foreground">ready for real product work.</span>`,
        `            </h1>`,
        `            <p className="max-w-2xl text-lg leading-8 text-muted-foreground">`,
        `              You have SSR, Cloudflare Workers deploy metadata, Tailwind v4, and shadcn-style primitives wired up. Edit`,
        `              <code className="mx-1 rounded-md bg-muted px-1.5 py-0.5 text-sm text-foreground">app/routes/home.tsx</code>`,
        `              and keep building from here.`,
        `            </p>`,
        `          </div>`,
        ``,
        `          <div className="flex flex-col gap-3 sm:flex-row">`,
        `            <Button asChild size="lg">`,
        `              <a href="https://reactrouter.com/start/framework/routing" target="_blank" rel="noreferrer">`,
        `                React Router docs`,
        `                <ArrowRight className="size-4" />`,
        `              </a>`,
        `            </Button>`,
        `            <Button asChild variant="outline" size="lg">`,
        `              <a href="https://ui.shadcn.com/docs/components" target="_blank" rel="noreferrer">`,
        `                Browse shadcn components`,
        `              </a>`,
        `            </Button>`,
        `          </div>`,
        `        </div>`,
        ``,
        `        <div className="grid gap-4">`,
        `          <Card className="border-primary/20 bg-background/85 shadow-2xl shadow-zinc-950/5 backdrop-blur">`,
        `            <CardHeader>`,
        `              <CardTitle className="flex items-center gap-2">`,
        `                <Cloud className="size-5 text-primary" />`,
        `                Cloudflare-ready`,
        `              </CardTitle>`,
        `              <CardDescription>Build output includes a worker bundle, native assets metadata, and deploy manifest.</CardDescription>`,
        `            </CardHeader>`,
        `          </Card>`,
        ``,
        `          <Card className="bg-background/75 backdrop-blur">`,
        `            <CardHeader>`,
        `              <CardTitle className="flex items-center gap-2">`,
        `                <Code2 className="size-5 text-primary" />`,
        `                Product patterns`,
        `              </CardTitle>`,
        `              <CardDescription>Use loaders, actions, and route modules for server-first fullstack behavior.</CardDescription>`,
        `            </CardHeader>`,
        `            <CardContent className="grid grid-cols-2 gap-3 text-sm text-muted-foreground">`,
        `              <div className="rounded-lg border bg-muted/40 p-3">SSR enabled</div>`,
        `              <div className="rounded-lg border bg-muted/40 p-3">shadcn-ready</div>`,
        `              <div className="rounded-lg border bg-muted/40 p-3">Tailwind v4</div>`,
        `              <div className="rounded-lg border bg-muted/40 p-3">Lucide icons</div>`,
        `            </CardContent>`,
        `          </Card>`,
        `        </div>`,
        `      </section>`,
        `    </main>`,
        `  );`,
        `}`,
      ]),
    },
    {
      path: "/app/entry.server.tsx",
      content: file([
        `import { renderToReadableStream } from "react-dom/server";`,
        `import type { AppLoadContext, EntryContext } from "react-router";`,
        `import { ServerRouter } from "react-router";`,
        ``,
        `export default async function handleRequest(`,
        `  request: Request,`,
        `  responseStatusCode: number,`,
        `  responseHeaders: Headers,`,
        `  routerContext: EntryContext,`,
        `  _loadContext: AppLoadContext,`,
        `): Promise<Response> {`,
        `  const body = await renderToReadableStream(`,
        `    <ServerRouter context={routerContext} url={request.url} />,`,
        `    {`,
        `      signal: request.signal,`,
        `      onError(error: unknown) {`,
        `        console.error(error);`,
        `        responseStatusCode = 500;`,
        `      },`,
        `    },`,
        `  );`,
        `  responseHeaders.set("Content-Type", "text/html");`,
        `  return new Response(body, { headers: responseHeaders, status: responseStatusCode });`,
        `}`,
      ]),
    },
    {
      path: "/workers/app.ts",
      content: file([
        `import { createRequestHandler } from "react-router";`,
        ``,
        `interface Env {`,
        `  ASSETS?: { fetch(request: Request): Promise<Response> | Response };`,
        `}`,
        ``,
        `const requestHandler = createRequestHandler(`,
        `  () => import("virtual:react-router/server-build"),`,
        `  import.meta.env.MODE,`,
        `);`,
        ``,
        `function shouldServeAsset(request: Request): boolean {`,
        `  const pathname = new URL(request.url).pathname;`,
        `  return pathname.startsWith("/assets/") || pathname.includes(".") || pathname === "/robots.txt";`,
        `}`,
        ``,
        `export default {`,
        `  async fetch(request: Request, env: Env, ctx: ExecutionContext) {`,
        `    if (env.ASSETS && shouldServeAsset(request)) {`,
        `      const assetResponse = await env.ASSETS.fetch(request);`,
        `      if (assetResponse.status !== 404) return assetResponse;`,
        `    }`,
        `    return requestHandler(request, { cloudflare: { env, ctx } });`,
        `  },`,
        `} satisfies ExportedHandler<Env>;`,
      ]),
    },
    {
      path: "/public/robots.txt",
      content: file([`User-agent: *`, `Allow: /`]),
    },
    {
      path: "/public/favicon.svg",
      content: file([
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="camelAI app icon">`,
        `  <rect width="64" height="64" rx="18" fill="#18181b"/>`,
        `  <path d="M18 40c6 7 22 7 28 0" fill="none" stroke="#fafafa" stroke-width="5" stroke-linecap="round"/>`,
        `  <path d="M20 25h24" stroke="#a1a1aa" stroke-width="5" stroke-linecap="round"/>`,
        `  <circle cx="25" cy="33" r="3" fill="#fafafa"/>`,
        `  <circle cx="39" cy="33" r="3" fill="#fafafa"/>`,
        `</svg>`,
      ]),
    },
    {
      path: "/public/og-image.svg",
      content: file([
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" role="img" aria-label="${svgProjectName} preview">`,
        `  <rect width="1200" height="630" fill="#fafafa"/>`,
        `  <circle cx="1040" cy="90" r="260" fill="#e4e4e7"/>`,
        `  <circle cx="180" cy="560" r="220" fill="#f4f4f5"/>`,
        `  <rect x="90" y="90" width="1020" height="450" rx="42" fill="#ffffff" stroke="#d4d4d8" stroke-width="3"/>`,
        `  <text x="150" y="245" fill="#18181b" font-family="Inter, Arial, sans-serif" font-size="42" font-weight="700">camelAI React Router app</text>`,
        `  <text x="150" y="350" fill="#18181b" font-family="Inter, Arial, sans-serif" font-size="78" font-weight="800">${svgProjectName}</text>`,
        `  <text x="150" y="430" fill="#71717a" font-family="Inter, Arial, sans-serif" font-size="30">Tailwind + shadcn-style primitives on Cloudflare Workers</text>`,
        `</svg>`,
      ]),
    },
    {
      path: "/scripts/build-manifest.mjs",
      content: file([
        `import { execFileSync } from "node:child_process";`,
        `import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";`,
        ``,
        `mkdirSync("build/server", { recursive: true });`,
        ``,
        `const workerEntryPath = "build/server/_cf_worker_entry.js";`,
        `const workerEntry = [`,
        `  'import { createRequestHandler } from "react-router";',`,
        `  'import * as build from "./index.js";',`,
        `  '',`,
        `  'const handler = createRequestHandler(build, "production");',`,
        `  '',`,
        `  'function shouldServeAsset(request) {',`,
        `  '  const pathname = new URL(request.url).pathname;',`,
        `  '  return pathname.startsWith("/assets/") || pathname.includes(".") || pathname === "/robots.txt";',`,
        `  '}',`,
        `  '',`,
        `  'export default {',`,
        `  '  async fetch(request, env, ctx) {',`,
        `  '    if (env.ASSETS && shouldServeAsset(request)) {',`,
        `  '      const assetResponse = await env.ASSETS.fetch(request);',`,
        `  '      if (assetResponse.status !== 404) return assetResponse;',`,
        `  '    }',`,
        `  '    return handler(request, { cloudflare: { env, ctx } });',`,
        `  '  },',`,
        `  '};',`,
        `].join("\\n");`,
        `writeFileSync(workerEntryPath, workerEntry + "\\n");`,
        ``,
        `execFileSync("node_modules/.bin/esbuild", [`,
        `  workerEntryPath,`,
        `  "--bundle",`,
        `  "--format=esm",`,
        `  "--platform=browser",`,
        `  "--conditions=workerd,worker,browser",`,
        `  "--external:cloudflare:*",`,
        `  "--external:node:*",`,
        `  "--external:util",`,
        `  "--external:crypto",`,
        `  "--external:async_hooks",`,
        `  "--external:stream",`,
        `  "--external:buffer",`,
        `  "--external:events",`,
        `  "--outfile=build/server/worker.js",`,
        `], { stdio: "inherit" });`,
        ``,
        `rmSync(workerEntryPath, { force: true });`,
        ``,
        `const rawConfig = readFileSync("wrangler.jsonc", "utf8");`,
        `const config = JSON.parse(rawConfig.replace(/\\/\\/[^\\n]*/g, "").replace(/,(\\s*[}\\]])/g, "$1"));`,
        `const manifest = {`,
        `  name: config.name,`,
        `  main_module: "worker.js",`,
        `  compatibility_date: config.compatibility_date,`,
        `  compatibility_flags: config.compatibility_flags ?? [],`,
        `  assets: { directory: "../client", binding: "ASSETS" },`,
        `};`,
        `writeFileSync("build/server/wrangler.json", JSON.stringify(manifest, null, 2) + "\\n");`,
        `console.log("build/server/wrangler.json written.");`,
      ]),
    },
    {
      path: "/README.md",
      content: file([
        `# ${projectName}`,
        ``,
        `React Router SSR scaffolded by camelAI with Tailwind v4 and shadcn-style UI primitives.`,
        ``,
        `## Commands`,
        ``,
        "- `bun install` installs explicit dependencies and CLIs.",
        "- `bun run dev` starts React Router local development.",
        "- `bun run typecheck` regenerates React Router route types and checks TypeScript.",
        "- `bun run build` runs `react-router build`, bundles a Cloudflare Worker wrapper, and writes `build/server/wrangler.json` for `deploy_project`.",
        "- `bun run deploy` is included for compatibility; camelAI's `deploy_project` uses the platform direct-deploy path.",
        "- Add more UI with `bunx --bun shadcn@latest add <component>`; `components.json`, `app/app.css`, and `~/lib/utils` are already configured.",
        ``,
        "Build scripts must declare every CLI they use in `dependencies` or `devDependencies`; package scripts can then resolve those binaries from `node_modules/.bin`.",
      ]),
    },
  ];
}

export function defaultProjectScaffoldFiles(
  projectName: string,
  template: ProjectScaffoldTemplate,
  scriptName: string,
): ProjectScaffoldFile[] {
  if (template === "react-router") return defaultReactRouterScaffoldFiles(projectName, scriptName);
  return defaultWorkerScaffoldFiles(projectName, scriptName, template);
}
