#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import {
  defaultProjectName,
  envFile,
  repoRoot,
  runtimeServiceDir,
  writeEnvValue,
} from "./selfhost-common.mjs";

const force = process.argv.includes("--force");

if (existsSync(envFile) && !force) {
  console.error(`${path.relative(repoRoot, envFile)} already exists.`);
  console.error("Use `bun run selfhost:init -- --force` to regenerate it.");
  process.exit(1);
}

const runtimeDir = runtimeServiceDir();
const values = {
  COMPOSE_PROJECT_NAME: defaultProjectName,
  SELFHOST_BIND_ADDRESS: "127.0.0.1",
  SELFHOST_APP_PORT: "3001",
  SELFHOST_PUBLIC_BASE_URL: "http://localhost:3001",
  SELFHOST_INTERNAL_APP_URL: "http://app:3001",
  LOCAL_APP_VANITY_DOMAIN: "",
  LOCAL_APP_IFRAME_DOMAIN: "",
  PROJECT_RUNTIME_SERVICE_DIR: runtimeDir,
  PROJECT_RUNTIME_HOST_STATE_DIR: path.join(repoRoot, ".selfhost", "project-runtime"),
  PROJECT_RUNTIME_IMAGE: "project-runtime-basic:latest",
  PROJECT_RUNTIME_IMAGE_DOCKERFILE: "Dockerfile.sandbox",
  PROJECT_RUNTIME_ENABLE_PROJECT_QUOTA: "0",
  PROJECT_RUNTIME_CONTAINER_USER: "claude",
  PROJECT_RUNTIME_CONTAINER_HOME: "/workspace",
  PROJECT_RUNTIME_CONTAINER_WORKDIR: "/workspace",
  PROJECT_RUNTIME_CONTAINER_NETWORK_MODE: `${defaultProjectName}_default`,
  PROJECT_RUNTIME_DOCKER_PROXY_BASE_URL: "http://project-runtime:4411",
  CONTAINER_RUNTIME: "runc",
  CLOUDFLARE_ACCESS_TEAM_DOMAIN: "",
  CLOUDFLARE_ACCESS_AUD: "",
  CLOUDFLARE_ACCESS_AUDS: "",
  CLOUDFLARE_ACCESS_ORG_MAP: "",
  CLOUDFLARE_ACCESS_ORG_CLAIMS: "",
  CLOUDFLARE_ACCESS_ORG_GROUP_PREFIX: "",
  CLOUDFLARE_ACCESS_ADMIN_GROUP_PREFIX: "",
  CLOUDFLARE_ACCESS_DEFAULT_ORG_NAME: "",
  CLOUDFLARE_ACCESS_REQUIRED_EMAIL_DOMAIN: "",
  POMERIUM_JWKS_URL: "",
  POMERIUM_AUTHENTICATE_URL: "",
  POMERIUM_ISSUER: "",
  POMERIUM_AUDIENCE: "",
  POMERIUM_ORG_MAP: "",
  POMERIUM_ORG_CLAIMS: "",
  POMERIUM_ORG_GROUP_PREFIX: "",
  POMERIUM_ADMIN_GROUP_PREFIX: "",
  POMERIUM_DEFAULT_ORG_NAME: "",
  POMERIUM_REQUIRED_EMAIL_DOMAIN: "",
  SELFHOST_AI_PROVIDER: "",
  SELFHOST_AI_API_KEY: "",
  SELFHOST_AI_BASE_URL: "",
  SELFHOST_AI_MODEL: "",
  SELFHOST_AI_NAME: "",
  SELFHOST_AI_AUTH_TYPE: "bearer",
  SELFHOST_AI_API: "openai-completions",
  SELFHOST_AI_AWS_REGION: "us-east-1",
  TOKEN_SIGNING_SECRET: secret(),
  INTEGRATION_SECRET_KEY: secret(),
  PROJECT_RUNTIME_PROXY_SECRET: secret(),
  LOCAL_ARTIFACTS_SECRET: secret(),
};

const content = `# camelAI self-host configuration.
# Generated by \`bun run selfhost:init\`.
# Keep this file private; it contains authentication and token-signing secrets.

${Object.entries(values)
  .map(([key, value]) => `${key}=${writeEnvValue(value)}`)
  .join("\n")}
`;

await fs.writeFile(envFile, content, { mode: 0o600 });
console.log(`Wrote ${path.relative(repoRoot, envFile)}.`);
console.log("Next steps:");
console.log("  bun run selfhost:doctor");
console.log("  bun run selfhost:up");

function secret() {
  return randomBytes(32).toString("base64url");
}
